apiVersion: v1
kind: Secret
metadata:
  name: planora-db-secret
  namespace: planora
type: Opaque
stringData:
  ConnectionStrings__HangfireConnectionString: "Host=planora-postgres-production.calakik6yf3z.us-east-1.rds.amazonaws.com;Port=5432;Database=PlanoraHangfire;Username=planora_admin;Password=F$N(z)%01EEbO&q<;SSL Mode=Require;Trust Server Certificate=true"
  ConnectionStrings__ProdCS: "Host=planora-postgres-production.calakik6yf3z.us-east-1.rds.amazonaws.com;Port=5432;Database=PlanoraDb;Username=planora_admin;Password=F$N(z)%01EEbO&q<;SSL Mode=Require;Trust Server Certificate=true"
  ConnectionMode: "Prod"
---
apiVersion: v1
kind: Secret
metadata:
  name: planora-redis-secret
  namespace: planora
type: Opaque
stringData:
  ConnectionStrings__RedisConnectionString: "master.planora-redis-production.wyb4ol.use1.cache.amazonaws.com:6379,ssl=true,abortConnect=false"
---
apiVersion: v1
kind: Secret
metadata:
  name: planora-jwt-secret
  namespace: planora
type: Opaque
stringData:
  JWTSETTINGS__SECRETKEY: "WE8(s7=JrU]2e=JuM?qy50CxN*sdxKNrpYvX<K_8Jv8?]C_]:?-iUVMXAtxz&L@r"
---
apiVersion: v1
kind: Secret
metadata:
  name: planora-smtp-secret
  namespace: planora
type: Opaque
stringData:
  EMAILSETTINGS__PASSWORD: "mock-password"
  EMAILSETTINGS__SENDEREMAIL: "planora.ayair@gmail.com"
  EMAILSETTINGS__SENDERNAME: "Planora AI"
  EMAILSETTINGS__SMTPHOST: "smtp.gmail.com"
  EMAILSETTINGS__SMTPPORT: "587"
  EMAILSETTINGS__USERNAME: "planora.ayair@gmail.com"
  EMAILSETTINGS__USESSL: "true"
---
apiVersion: v1
kind: Secret
metadata:
  name: planora-hangfire-secret
  namespace: planora
type: Opaque
stringData:
  HANGFIRESETTINGS__PASSWORD: "*nJwx2%qRkWqZz)]"
  HANGFIRESETTINGS__USERNAME: "admin"
---
apiVersion: v1
kind: Secret
metadata:
  name: planora-ai-secret
  namespace: planora
type: Opaque
stringData:
  AIOPTIONS__APIKEY: "BSU<WYj3G+?=BV_G-e7*(b1GT0+(kD{a"
  AIOPTIONS__BASEURL: "http://ai-python.planora.svc.cluster.local"
---
apiVersion: v1
kind: Secret
metadata:
  name: planora-s3-secret
  namespace: planora
type: Opaque
stringData:
  AWS_BUCKET_NAME: "planora-ai-production-lq49e8"
  AWS_REGION: "us-east-1"
---

