apiVersion: v1
kind: Secret
metadata:
  name: planora-secrets
type: Opaque
stringData:
  db-connection-string: "Server=YOUR_RDS_ENDPOINT;Database=PlanoraProd;User Id=planora_admin;Password=YOUR_PASSWORD;"

  redis-connection-string: "YOUR_ELASTICACHE_ENDPOINT:6379"
  redis-url: "redis://YOUR_ELASTICACHE_ENDPOINT:6379"

  aws-access-key-id: "YOUR_IAM_ACCESS_KEY_ID"
  aws-secret-access-key: "YOUR_IAM_SECRET_ACCESS_KEY"
  aws-region: "us-east-1"
  aws-bucket-name: "planora-ai-production"
