// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetTopologySuite.Geometries;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Planora.Infrastructure.Persistence.Contexts;

#nullable disable

namespace Planora.Infrastructure.Migrations
{
    [DbContext(typeof(PlanoraDbContext))]
    [Migration("20260625121515_AddMissingContractFields")]
    partial class AddMissingContractFields
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.27")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "postgis");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text")
                        .HasColumnName("concurrency_stamp");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("name");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("normalized_name");

                    b.HasKey("Id")
                        .HasName("pk_asp_net_roles");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text")
                        .HasColumnName("claim_type");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text")
                        .HasColumnName("claim_value");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid")
                        .HasColumnName("role_id");

                    b.HasKey("Id")
                        .HasName("pk_asp_net_role_claims");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("ix_asp_net_role_claims_role_id");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text")
                        .HasColumnName("claim_type");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text")
                        .HasColumnName("claim_value");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_asp_net_user_claims");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_asp_net_user_claims_user_id");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text")
                        .HasColumnName("login_provider");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text")
                        .HasColumnName("provider_key");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text")
                        .HasColumnName("provider_display_name");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("LoginProvider", "ProviderKey")
                        .HasName("pk_asp_net_user_logins");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_asp_net_user_logins_user_id");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid")
                        .HasColumnName("role_id");

                    b.HasKey("UserId", "RoleId")
                        .HasName("pk_asp_net_user_roles");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("ix_asp_net_user_roles_role_id");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text")
                        .HasColumnName("login_provider");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Value")
                        .HasColumnType("text")
                        .HasColumnName("value");

                    b.HasKey("UserId", "LoginProvider", "Name")
                        .HasName("pk_asp_net_user_tokens");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Planora.Domain.Analysis.BoreholeResult", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AnalysisJobId")
                        .HasColumnType("uuid")
                        .HasColumnName("analysis_job_id");

                    b.Property<double>("CoveragePercentage")
                        .HasColumnType("double precision")
                        .HasColumnName("coverage_percentage");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<string>("Currency")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("currency");

                    b.Property<string>("GridSize")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("grid_size");

                    b.Property<int>("MinimumRequired")
                        .HasColumnType("integer")
                        .HasColumnName("minimum_required");

                    b.Property<int>("OptimalCount")
                        .HasColumnType("integer")
                        .HasColumnName("optimal_count");

                    b.Property<int>("OptimizedBoreholeCount")
                        .HasColumnType("integer")
                        .HasColumnName("optimized_borehole_count");

                    b.Property<decimal>("OptimizedEstimatedCost")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("optimized_estimated_cost");

                    b.Property<string>("PlacementGeoJsonUrl")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("placement_geo_json_url");

                    b.Property<string>("PlacementPointsJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("placement_points_json");

                    b.Property<string>("PlacementStrategy")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("placement_strategy");

                    b.Property<decimal>("SavingsAmount")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("savings_amount");

                    b.Property<double>("SavingsPercentage")
                        .HasColumnType("double precision")
                        .HasColumnName("savings_percentage");

                    b.Property<int>("TraditionalBoreholeCount")
                        .HasColumnType("integer")
                        .HasColumnName("traditional_borehole_count");

                    b.Property<decimal>("TraditionalEstimatedCost")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("traditional_estimated_cost");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.HasKey("Id")
                        .HasName("pk_borehole_results");

                    b.HasIndex("AnalysisJobId")
                        .HasDatabaseName("ix_borehole_results_analysis_job_id");

                    b.ToTable("BoreholeResults", (string)null);
                });

            modelBuilder.Entity("Planora.Domain.Analysis.RiskResult", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AnalysisJobId")
                        .HasColumnType("uuid")
                        .HasColumnName("analysis_job_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<string>("ExpansiveSoilFactorsJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("expansive_soil_factors_json");

                    b.Property<string>("ExpansiveSoilLevel")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("expansive_soil_level");

                    b.Property<int>("ExpansiveSoilRisk")
                        .HasColumnType("integer")
                        .HasColumnName("expansive_soil_risk");

                    b.Property<string>("FloodFactorsJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("flood_factors_json");

                    b.Property<string>("FloodGeoJsonUrl")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("flood_geo_json_url");

                    b.Property<string>("FloodLevel")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("flood_level");

                    b.Property<int>("FloodRiskScore")
                        .HasColumnType("integer")
                        .HasColumnName("flood_risk_score");

                    b.Property<string>("LiquefactionFactorsJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("liquefaction_factors_json");

                    b.Property<string>("LiquefactionLevel")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("liquefaction_level");

                    b.Property<string>("LiquefactionMethodology")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("liquefaction_methodology");

                    b.Property<int>("LiquefactionRisk")
                        .HasColumnType("integer")
                        .HasColumnName("liquefaction_risk");

                    b.Property<string>("LiquefactionSusceptibility")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("liquefaction_susceptibility");

                    b.Property<string>("MitigationSuggestionsJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("mitigation_suggestions_json");

                    b.Property<string>("OverallRiskLevel")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("overall_risk_level");

                    b.Property<int>("OverallRiskScore")
                        .HasColumnType("integer")
                        .HasColumnName("overall_risk_score");

                    b.Property<double?>("ReplacementDepth")
                        .HasColumnType("double precision")
                        .HasColumnName("replacement_depth");

                    b.Property<string>("RiskHeatmapTileUrl")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("risk_heatmap_tile_url");

                    b.Property<string>("SeismicFactorsJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("seismic_factors_json");

                    b.Property<string>("SeismicLevel")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("seismic_level");

                    b.Property<int>("SeismicRiskScore")
                        .HasColumnType("integer")
                        .HasColumnName("seismic_risk_score");

                    b.Property<string>("SeismicSource")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("seismic_source");

                    b.Property<string>("SeismicZone")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("seismic_zone");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.HasKey("Id")
                        .HasName("pk_risk_results");

                    b.HasIndex("AnalysisJobId")
                        .HasDatabaseName("ix_risk_results_analysis_job_id");

                    b.ToTable("RiskResults", (string)null);
                });

            modelBuilder.Entity("Planora.Domain.Analysis.SoilResult", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<double?>("AiConfidence")
                        .HasColumnType("double precision")
                        .HasColumnName("ai_confidence");

                    b.Property<Guid>("AnalysisJobId")
                        .HasColumnType("uuid")
                        .HasColumnName("analysis_job_id");

                    b.Property<string>("BearingCapacityCategory")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("bearing_capacity_category");

                    b.Property<double>("BearingCapacityEstimate")
                        .HasColumnType("double precision")
                        .HasColumnName("bearing_capacity_estimate");

                    b.Property<double?>("BearingConfidence")
                        .HasColumnType("double precision")
                        .HasColumnName("bearing_confidence");

                    b.Property<string>("BearingFramework")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("bearing_framework");

                    b.Property<double?>("BearingMaxKpa")
                        .HasColumnType("double precision")
                        .HasColumnName("bearing_max_kpa");

                    b.Property<double?>("BearingMinKpa")
                        .HasColumnType("double precision")
                        .HasColumnName("bearing_min_kpa");

                    b.Property<string>("BearingModelName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("bearing_model_name");

                    b.Property<string>("BearingRange")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("bearing_range");

                    b.Property<bool?>("BearingShapEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("bearing_shap_enabled");

                    b.Property<string>("BearingTrafficLight")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("bearing_traffic_light");

                    b.Property<double?>("BearingTrainingR2")
                        .HasColumnType("double precision")
                        .HasColumnName("bearing_training_r2");

                    b.Property<double?>("BsiMean")
                        .HasColumnType("double precision")
                        .HasColumnName("bsi_mean");

                    b.Property<double>("BulkDensity")
                        .HasColumnType("double precision")
                        .HasColumnName("bulk_density");

                    b.Property<string>("BulkDensityUnit")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("bulk_density_unit");

                    b.Property<double?>("Cec")
                        .HasColumnType("double precision")
                        .HasColumnName("cec");

                    b.Property<double>("ClayPercent")
                        .HasColumnType("double precision")
                        .HasColumnName("clay_percent");

                    b.Property<string>("CompositionUnit")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("composition_unit");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<string>("DataSourcesJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("data_sources_json");

                    b.Property<string>("DepthProfileImageUrl")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("depth_profile_image_url");

                    b.Property<string>("FeatureImportanceJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("feature_importance_json");

                    b.Property<string>("FloorCountCategory")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("floor_count_category");

                    b.Property<string>("HeatmapTileUrl")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("heatmap_tile_url");

                    b.Property<int?>("MaxFloorsWithoutDeepFoundation")
                        .HasColumnType("integer")
                        .HasColumnName("max_floors_without_deep_foundation");

                    b.Property<string>("MultiDepthProfileJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("multi_depth_profile_json");

                    b.Property<double?>("NdmiMean")
                        .HasColumnType("double precision")
                        .HasColumnName("ndmi_mean");

                    b.Property<double?>("NdviMean")
                        .HasColumnType("double precision")
                        .HasColumnName("ndvi_mean");

                    b.Property<double>("OrganicCarbon")
                        .HasColumnType("double precision")
                        .HasColumnName("organic_carbon");

                    b.Property<string>("OrganicCarbonUnit")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("organic_carbon_unit");

                    b.Property<double>("Ph")
                        .HasColumnType("double precision")
                        .HasColumnName("ph");

                    b.Property<string>("PrimaryType")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("primary_type");

                    b.Property<string>("RecommendedFoundation")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("recommended_foundation");

                    b.Property<double>("SandPercent")
                        .HasColumnType("double precision")
                        .HasColumnName("sand_percent");

                    b.Property<double>("SiltPercent")
                        .HasColumnType("double precision")
                        .HasColumnName("silt_percent");

                    b.Property<string>("SoilFactorsJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("soil_factors_json");

                    b.Property<string>("SoilTypeGeoJsonUrl")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("soil_type_geo_json_url");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.Property<string>("UsdaClass")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("usda_class");

                    b.Property<double?>("WaterTableDepthMeters")
                        .HasColumnType("double precision")
                        .HasColumnName("water_table_depth_meters");

                    b.HasKey("Id")
                        .HasName("pk_soil_results");

                    b.HasIndex("AnalysisJobId")
                        .HasDatabaseName("ix_soil_results_analysis_job_id");

                    b.ToTable("SoilResults", (string)null);
                });

            modelBuilder.Entity("Planora.Domain.Analysis.TopographyResult", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AnalysisJobId")
                        .HasColumnType("uuid")
                        .HasColumnName("analysis_job_id");

                    b.Property<string>("ContourGeoJsonUrl")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("contour_geo_json_url");

                    b.Property<double>("ContourInterval")
                        .HasColumnType("double precision")
                        .HasColumnName("contour_interval");

                    b.Property<string>("CopernicusDemVersion")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("copernicus_dem_version");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<string>("Crs")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("crs");

                    b.Property<double>("CutVolume")
                        .HasColumnType("double precision")
                        .HasColumnName("cut_volume");

                    b.Property<string>("DemRasterUrl")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("dem_raster_url");

                    b.Property<double>("ElevationMax")
                        .HasColumnType("double precision")
                        .HasColumnName("elevation_max");

                    b.Property<double>("ElevationMean")
                        .HasColumnType("double precision")
                        .HasColumnName("elevation_mean");

                    b.Property<double>("ElevationMin")
                        .HasColumnType("double precision")
                        .HasColumnName("elevation_min");

                    b.Property<string>("ElevationTileUrl")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("elevation_tile_url");

                    b.Property<double>("FillVolume")
                        .HasColumnType("double precision")
                        .HasColumnName("fill_volume");

                    b.Property<double>("NetVolume")
                        .HasColumnType("double precision")
                        .HasColumnName("net_volume");

                    b.Property<int?>("PixelResolutionMeters")
                        .HasColumnType("integer")
                        .HasColumnName("pixel_resolution_meters");

                    b.Property<string>("PondingGeoJsonUrl")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("ponding_geo_json_url");

                    b.Property<double?>("PondingTotalArea")
                        .HasColumnType("double precision")
                        .HasColumnName("ponding_total_area");

                    b.Property<int?>("PondingZonesCount")
                        .HasColumnType("integer")
                        .HasColumnName("ponding_zones_count");

                    b.Property<int?>("ProcessingTimeSeconds")
                        .HasColumnType("integer")
                        .HasColumnName("processing_time_seconds");

                    b.Property<string>("SlopeDistributionJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("slope_distribution_json");

                    b.Property<string>("SlopeRasterUrl")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("slope_raster_url");

                    b.Property<string>("SlopeTileUrl")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("slope_tile_url");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.HasKey("Id")
                        .HasName("pk_topography_results");

                    b.HasIndex("AnalysisJobId")
                        .HasDatabaseName("ix_topography_results_analysis_job_id");

                    b.ToTable("TopographyResults", (string)null);
                });

            modelBuilder.Entity("Planora.Domain.AnalysisJob.AnalysisJob", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("error_message");

                    b.Property<Guid>("ParcelId")
                        .HasColumnType("uuid")
                        .HasColumnName("parcel_id");

                    b.Property<string>("PythonJobId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("python_job_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("status");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("type");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.HasKey("Id")
                        .HasName("pk_analysis_jobs");

                    b.HasIndex("ParcelId")
                        .HasDatabaseName("ix_analysis_jobs_parcel_id");

                    b.HasIndex("PythonJobId")
                        .IsUnique()
                        .HasDatabaseName("ix_analysis_jobs_python_job_id");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_analysis_jobs_status");

                    b.ToTable("AnalysisJobs", (string)null);
                });

            modelBuilder.Entity("Planora.Domain.Common.AuthAuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("action");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<string>("Metadata")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("metadata");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_auth_audit_logs");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_auth_audit_logs_user_id");

                    b.ToTable("auth_audit_logs", (string)null);
                });

            modelBuilder.Entity("Planora.Domain.Common.OtpRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<string>("Purpose")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("purpose");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.Property<DateTime?>("UsedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("used_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_otp_records");

                    b.HasIndex("UserId", "Purpose")
                        .HasDatabaseName("ix_otp_records_user_id_purpose");

                    b.ToTable("otp_records", (string)null);
                });

            modelBuilder.Entity("Planora.Domain.Common.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("token");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_refresh_tokens");

                    b.HasIndex("Token")
                        .IsUnique()
                        .HasDatabaseName("ix_refresh_tokens_token");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_refresh_tokens_user_id");

                    b.ToTable("refresh_tokens", (string)null);
                });

            modelBuilder.Entity("Planora.Domain.Notifications.Notification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<string>("Data")
                        .HasColumnType("jsonb")
                        .HasColumnName("data");

                    b.Property<bool>("IsRead")
                        .HasColumnType("boolean")
                        .HasColumnName("is_read");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("message");

                    b.Property<DateTime?>("ReadAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("read_at");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("title");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("type");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_notifications");

                    b.HasIndex("UserId", "IsRead", "CreatedAt")
                        .IsDescending(false, false, true)
                        .HasDatabaseName("IX_Notifications_UserId_IsRead_CreatedAt");

                    b.ToTable("Notifications", (string)null);
                });

            modelBuilder.Entity("Planora.Domain.Parcels.Parcel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("AreaHectares")
                        .HasColumnType("numeric")
                        .HasColumnName("area_hectares");

                    b.Property<Polygon>("Boundary")
                        .IsRequired()
                        .HasColumnType("geometry")
                        .HasColumnName("boundary");

                    b.Property<Point>("Centroid")
                        .IsRequired()
                        .HasColumnType("geometry")
                        .HasColumnName("centroid");

                    b.Property<string>("Country")
                        .HasColumnType("text")
                        .HasColumnName("country");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("deleted_by");

                    b.Property<string>("GeojsonKey")
                        .HasColumnType("text")
                        .HasColumnName("geojson_key");

                    b.Property<string>("Governorate")
                        .HasColumnType("text")
                        .HasColumnName("governorate");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_parcels");

                    b.HasIndex("Boundary")
                        .HasDatabaseName("ix_parcels_boundary");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Boundary"), "GIST");

                    b.HasIndex("Centroid")
                        .HasDatabaseName("ix_parcels_centroid");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Centroid"), "GIST");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_parcels_user_id");

                    b.ToTable("Parcels", (string)null);
                });

            modelBuilder.Entity("Planora.Domain.Payments.Payment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric")
                        .HasColumnName("amount");

                    b.Property<decimal>("AmountUsd")
                        .HasColumnType("numeric")
                        .HasColumnName("amount_usd");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("currency");

                    b.Property<string>("Gateway")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("gateway");

                    b.Property<string>("GatewayEventId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("gateway_event_id");

                    b.Property<string>("GatewayPaymentId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("gateway_payment_id");

                    b.Property<string>("RawPayload")
                        .HasColumnType("jsonb")
                        .HasColumnName("raw_payload");

                    b.Property<decimal?>("RefundAmount")
                        .HasColumnType("numeric")
                        .HasColumnName("refund_amount");

                    b.Property<string>("RefundReason")
                        .HasColumnType("text")
                        .HasColumnName("refund_reason");

                    b.Property<DateTime?>("RefundedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("refunded_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("status");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_payments");

                    b.HasIndex("GatewayEventId")
                        .IsUnique()
                        .HasDatabaseName("ix_payments_gateway_event_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_payments_user_id");

                    b.ToTable("Payments", (string)null);
                });

            modelBuilder.Entity("Planora.Domain.Reports.Report", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text")
                        .HasColumnName("error_message");

                    b.Property<int?>("EstimatedDurationMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("estimated_duration_minutes");

                    b.Property<string>("HangfireJobId")
                        .HasColumnType("text")
                        .HasColumnName("hangfire_job_id");

                    b.Property<Guid>("ParcelId")
                        .HasColumnType("uuid")
                        .HasColumnName("parcel_id");

                    b.Property<Guid?>("PaymentId")
                        .HasColumnType("uuid")
                        .HasColumnName("payment_id");

                    b.Property<DateTime?>("ProcessingCompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processing_completed_at");

                    b.Property<DateTime?>("ProcessingStartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processing_started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<string>("Tier")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("tier");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_reports");

                    b.HasIndex("ParcelId")
                        .HasDatabaseName("ix_reports_parcel_id");

                    b.HasIndex("PaymentId")
                        .HasDatabaseName("ix_reports_payment_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_reports_user_id");

                    b.ToTable("Reports", (string)null);
                });

            modelBuilder.Entity("Planora.Domain.Reports.ReportFile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content_type");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("file_name");

                    b.Property<long?>("FileSizeBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("file_size_bytes");

                    b.Property<int>("FileType")
                        .HasColumnType("integer")
                        .HasColumnName("file_type");

                    b.Property<Guid>("ReportId")
                        .HasColumnType("uuid")
                        .HasColumnName("report_id");

                    b.Property<string>("S3Key")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("s3key");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.HasKey("Id")
                        .HasName("pk_report_files");

                    b.HasIndex("ReportId")
                        .HasDatabaseName("ix_report_files_report_id");

                    b.ToTable("report_files", (string)null);
                });

            modelBuilder.Entity("Planora.Domain.Reports.ReportModule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text")
                        .HasColumnName("error_message");

                    b.Property<long?>("FileSizeBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("file_size_bytes");

                    b.Property<string>("ModuleType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("module_type");

                    b.Property<string>("OutputMetadata")
                        .HasColumnType("jsonb")
                        .HasColumnName("output_metadata");

                    b.Property<string>("OutputS3Key")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("output_s3key");

                    b.Property<int?>("PageCount")
                        .HasColumnType("integer")
                        .HasColumnName("page_count");

                    b.Property<Guid>("ReportId")
                        .HasColumnType("uuid")
                        .HasColumnName("report_id");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.HasKey("Id")
                        .HasName("pk_report_modules");

                    b.HasIndex("OutputMetadata")
                        .HasDatabaseName("ix_report_modules_output_metadata");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("OutputMetadata"), "GIN");

                    b.HasIndex("ReportId", "ModuleType")
                        .IsUnique()
                        .HasDatabaseName("ix_report_modules_report_id_module_type");

                    b.ToTable("ReportModules", (string)null);
                });

            modelBuilder.Entity("Planora.Infrastructure.Identity.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer")
                        .HasColumnName("access_failed_count");

                    b.Property<string>("CompanyName")
                        .HasColumnType("text")
                        .HasColumnName("company_name");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text")
                        .HasColumnName("concurrency_stamp");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("deleted_by");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("email");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean")
                        .HasColumnName("email_confirmed");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("first_name");

                    b.Property<bool>("FreeTrialUsed")
                        .HasColumnType("boolean")
                        .HasColumnName("free_trial_used");

                    b.Property<bool>("IsBanned")
                        .HasColumnType("boolean")
                        .HasColumnName("is_banned");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<string>("JobTitle")
                        .HasColumnType("text")
                        .HasColumnName("job_title");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_login_at");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("last_name");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("lockout_enabled");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("lockout_end");

                    b.Property<int>("LoginCount")
                        .HasColumnType("integer")
                        .HasColumnName("login_count");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("normalized_email");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("normalized_user_name");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text")
                        .HasColumnName("phone_number");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean")
                        .HasColumnName("phone_number_confirmed");

                    b.Property<string>("ProjectName")
                        .HasColumnType("text")
                        .HasColumnName("project_name");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("role");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text")
                        .HasColumnName("security_stamp");

                    b.Property<string>("SubscriptionTier")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("subscription_tier");

                    b.Property<DateTime?>("TermsAcceptedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("terms_accepted_at");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("two_factor_enabled");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("user_name");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_asp_net_role_claims_asp_net_roles_role_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("Planora.Infrastructure.Identity.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_asp_net_user_claims_asp_net_users_user_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("Planora.Infrastructure.Identity.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_asp_net_user_logins_asp_net_users_user_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_asp_net_user_roles_asp_net_roles_role_id");

                    b.HasOne("Planora.Infrastructure.Identity.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_asp_net_user_roles_asp_net_users_user_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("Planora.Infrastructure.Identity.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_asp_net_user_tokens_asp_net_users_user_id");
                });

            modelBuilder.Entity("Planora.Domain.Analysis.BoreholeResult", b =>
                {
                    b.HasOne("Planora.Domain.AnalysisJob.AnalysisJob", null)
                        .WithMany()
                        .HasForeignKey("AnalysisJobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_borehole_results_analysis_jobs_analysis_job_id");
                });

            modelBuilder.Entity("Planora.Domain.Analysis.RiskResult", b =>
                {
                    b.HasOne("Planora.Domain.AnalysisJob.AnalysisJob", null)
                        .WithMany()
                        .HasForeignKey("AnalysisJobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_risk_results_analysis_jobs_analysis_job_id");
                });

            modelBuilder.Entity("Planora.Domain.Analysis.SoilResult", b =>
                {
                    b.HasOne("Planora.Domain.AnalysisJob.AnalysisJob", null)
                        .WithMany()
                        .HasForeignKey("AnalysisJobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_soil_results_analysis_jobs_analysis_job_id");
                });

            modelBuilder.Entity("Planora.Domain.Analysis.TopographyResult", b =>
                {
                    b.HasOne("Planora.Domain.AnalysisJob.AnalysisJob", null)
                        .WithMany()
                        .HasForeignKey("AnalysisJobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_topography_results_analysis_jobs_analysis_job_id");
                });

            modelBuilder.Entity("Planora.Domain.AnalysisJob.AnalysisJob", b =>
                {
                    b.HasOne("Planora.Domain.Parcels.Parcel", null)
                        .WithMany()
                        .HasForeignKey("ParcelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_analysis_jobs_parcels_parcel_id");

                    b.OwnsOne("Planora.Domain.AnalysisJob.AnalysisOptions", "Options", b1 =>
                        {
                            b1.Property<Guid>("AnalysisJobId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<decimal?>("ContourInterval")
                                .HasPrecision(10, 4)
                                .HasColumnType("numeric(10,4)")
                                .HasColumnName("options_contour_interval");

                            b1.Property<bool>("IncludeBearing")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("boolean")
                                .HasDefaultValue(false)
                                .HasColumnName("options_include_bearing");

                            b1.Property<bool>("IncludeBorehole")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("boolean")
                                .HasDefaultValue(false)
                                .HasColumnName("options_include_borehole");

                            b1.Property<bool>("IncludeRisk")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("boolean")
                                .HasDefaultValue(false)
                                .HasColumnName("options_include_risk");

                            b1.Property<bool>("IncludeSoil")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("boolean")
                                .HasDefaultValue(false)
                                .HasColumnName("options_include_soil");

                            b1.Property<bool>("IncludeTopography")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("boolean")
                                .HasDefaultValue(false)
                                .HasColumnName("options_include_topography");

                            b1.Property<string>("ReferencePlane")
                                .HasMaxLength(64)
                                .HasColumnType("character varying(64)")
                                .HasColumnName("options_reference_plane");

                            b1.Property<string>("SlopeCategories")
                                .HasColumnType("jsonb")
                                .HasColumnName("options_slope_categories");

                            b1.Property<string>("SoilDepths")
                                .HasColumnType("jsonb")
                                .HasColumnName("options_soil_depths");

                            b1.HasKey("AnalysisJobId");

                            b1.ToTable("AnalysisJobs", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("AnalysisJobId")
                                .HasConstraintName("fk_analysis_jobs_analysis_jobs_id");
                        });

                    b.Navigation("Options");
                });

            modelBuilder.Entity("Planora.Domain.Parcels.Parcel", b =>
                {
                    b.HasOne("Planora.Infrastructure.Identity.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_parcels_asp_net_users_user_id");
                });

            modelBuilder.Entity("Planora.Domain.Payments.Payment", b =>
                {
                    b.HasOne("Planora.Infrastructure.Identity.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_payments_asp_net_users_user_id");
                });

            modelBuilder.Entity("Planora.Domain.Reports.Report", b =>
                {
                    b.HasOne("Planora.Domain.Parcels.Parcel", null)
                        .WithMany()
                        .HasForeignKey("ParcelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_reports_parcels_parcel_id");

                    b.HasOne("Planora.Domain.Payments.Payment", null)
                        .WithMany()
                        .HasForeignKey("PaymentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_reports_payments_payment_id");

                    b.HasOne("Planora.Infrastructure.Identity.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_reports_asp_net_users_user_id");
                });

            modelBuilder.Entity("Planora.Domain.Reports.ReportFile", b =>
                {
                    b.HasOne("Planora.Domain.Reports.Report", null)
                        .WithMany("Files")
                        .HasForeignKey("ReportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_report_files_reports_report_id");
                });

            modelBuilder.Entity("Planora.Domain.Reports.ReportModule", b =>
                {
                    b.HasOne("Planora.Domain.Reports.Report", null)
                        .WithMany("Modules")
                        .HasForeignKey("ReportId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_report_modules_reports_report_id");
                });

            modelBuilder.Entity("Planora.Domain.Reports.Report", b =>
                {
                    b.Navigation("Files");

                    b.Navigation("Modules");
                });
#pragma warning restore 612, 618
        }
    }
}
